#!/usr/bin/env ruby
# frozen_string_literal: true

require "commander/import"
require "branchbot"

program :name, 'branchbot'
program :version, Branchbot::VERSION
program :description, "Saves and restores the state of your local database as you work on different git branches."

command :switch do |cmd|
  cmd.syntax = "branchbot switch [options]"
  cmd.option '--from FROM_REF', String, 'ref switching from'
  cmd.option '--app-root relative/path/to/app', String, 'path to app root relative to project root (default: .)'
  cmd.option '--no-db-config-erb', 'Disables interpreting the database config as ERB before parsing YML'

  cmd.action do |args, options|
    unless options.from
      say "--from required"
      next
    end

    options.default app_root: '.'
    options.default no_db_config_erb: true

    # Invert --no-db-config-erb option since it's normally false
    # when no value is specified with the switch
    no_db_config_erb = !options.no_db_config_erb

    Branchbot::BranchSwitcher.new(
      app_root: options.app_root,
      erb_in_database_yml: !no_db_config_erb
    ).switch_from(options.from)
  end
end
