#!/usr/bin/env ruby
# frozen_string_literal: true

require "commander/import"
require "branchbot"

program :name, 'branchbot'
program :version, Branchbot::VERSION
program :description, "Saves and restores the state of your local database as you work on different git branches."

command :switch do |cmd|
  cmd.syntax = "branchbot switch [options]"
  cmd.option '--from FROM_REF', String, 'ref switching from'
  cmd.option '--db-config-path path/to/database.yml', String, 'path to database.yml relative to project root (default: config/database.yml)'

  cmd.action do |args, options|
    unless options.from
      say "--from required"
      next
    end

    options.default db_config_path: 'config/database.yml'

    Branchbot::BranchSwitcher.new(
      database_yml_path: options.db_config_path
    ).switch_from(options.from)
  end
end
